# Generated by Django 5.1.1 on 2024-12-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
